[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aruism_ai"
version = "0.1.0"
authors = [
  { name="Taka-Aruism", email="author@example.com" },
]
description = "Aruism AI Project"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["src"]
